# Generated by Django 5.2.1 on 2025-06-05 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='emp_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_num', models.IntegerField(max_length=10)),
                ('emp_email', models.CharField(max_length=50)),
                ('emp_add', models.CharField(max_length=100)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.employees')),
            ],
        ),
    ]
