# Generated by Django 5.2.1 on 2025-06-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_details',
            name='emp_num',
            field=models.IntegerField(),
        ),
    ]
