# Generated by Django 5.2.1 on 2025-06-17 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_emp_details_emp_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_details',
            name='emp_num',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.employees', to_field='emp_id'),
        ),
    ]
